### ISSUE TITLE
validate html output

### ISSUE THREAD

**Issue by jbrgfx** [lmiller1990/electic#10]
Great ideas and nice CLI API.
The templates/index.html.exs might be improved as follows so that the source validates against the W3C validator (https://validator.w3.org/nu/#textarea):

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <%= for post <- posts do %><title><%= post.title%></title><% end %>
</head>
<body>
  <section><h1>
    <%= for post <- posts do %>
      <a href="<%= post.link %>">
        <%= post.title%>
      </a>
    </h1>
      <div class="intro">
        <%= post.intro %>
      </div>
      <br>
    <% end %>

  </section>
  <script src="index.js"></script>
</body>
</html>

```
Changelog:  
1.  added dynamic title generation;
2.  added heading to section; and
3.  moved script to body

**Comment by lmiller1990** [comment]
Hey,

Thanks for the comment. This repo is definitely in need of some updates. This sounds like a good idea. Another one I'd like to do is implement a proper CLI so you do not need to run `iex`.

Might look in to this one in the near future.
